name: ContinuousIntegration
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.0.100' # SDK Version to use.
    - run: build.cmd
