name: ContinuousIntegration
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@master
    - run: build.cmd
